application: mol-lab
version: points
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

inbound_services:
- channel_presence

handlers:

- url: /backend/points/.*
  script: points.py

- url: /_ah/channel/connected/.*
  script: points.py

- url: /_ah/channel/disconnected/.*
  script: points.py
    
- url: /js
  static_dir: js
