application: mol-lab
version: points
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:

- url: /backend/points/.*
  script: points.py

- url: /js
  static_dir: js
