# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: walter
  email: walter.jetz@yale.com

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- DirectoryName: mammals
   
  # Required MOL metadata (http://goo.gl/98r46)
  #  
  Required:
    accessrights: yes
    bibliographiccitation: citations
    breedingdomain: global
    contact: walter
    coverage: earth
    creator: walter
    date: 2001
    description: good
    email: walter.jetz@yale.com
    eventdate: 2001
    nonbreedingdomain: nowhere
    presencedefault: true
    publisher: yale
    samplingprotocol: amazing
    scientificname: puma concolor
    source: walter lab
    subject: puma range maps
    taxonomiccoverage: puma
    title: cool maps
    verbatimsrs: unknown

  # Optional MoL metadata (http://goo.gl/98r46)
  #
  Optional:
    accessright:    
    basemaps:    
    contributor:    
    enddateaccuracy:    
    format:    
    identifier:    
    language:    
    layertype:    
    mapcount:    
    maxregionsperspecies:    
    maxx:    
    maxy:    
    medianregionsperspecies:    
    minregionsperspecies:    
    minx:    
    miny:    
    relation:    
    rights:    
    samplingprotocol:    
    startdateaccuracy:    
    surveyintervals:    
    taxonomy:    
    type:

  # Mappings between collection DBF fields and MoL DBF fields: (http://goo.gl/UkzJW)
  #
  DBFMapping:

    # Required MoL DBF fields 
    #
    Required:
      areaid: OBJECTID
      bibliographiccitation: AREA
      polygonid: PERIMETER
      polygonname: ECO_NAME      

    # Optional MoL DBF fields
    #
    Optional:
      abundance:      
      abundancecomment:      
      abundancemakeup:      
      abundancemethod:      
      abundancesurveyarea:      
      abundanceunits:      
      areaname:      
      contributor:      
      dateend:      
      datestart:      
      distributioncomment:      
      dynamicproperties:      
      establishmentmeans:      
      infraspecificepithet:      
      later:      
      measurementcomment:      
      measurementmethod:      
      occurrencestatus:      
      population:      
      seasonality:      
      taxonid:      
      taxonremarks:
