# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: Jetz Lab 
  email: walter.jetz@yale.edu

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- DirectoryName: birds
   
  # Required MOL metadata (http://www.google.com/fusiontables/DataSource?dsrcid=1348212)
  #  
  Required:
    collectionorigin:       6
    collectionpresence:     6
    collectionseasonality:  6
    collectionstartdate:    2011
    contact: Walter Jetz
    contributor: Walter Jetz
    coverage:    global
    creator: Jetz Lab
    date: 2011
    description: Improved bird range maps.
    email: walter.jetz@yale.edu
    publisher:  Jetz Lab
    rights: Creative Commons Attribution-Share Alike 3.0 Unported license. http://creativecommons.org/licenses/by-sa/3.0/deed.en
    samplingprotocol: expert opinion
    scientificname: Aves
    source:  Jetz Lab
    subject: Jetz Lab
    taxonomiccoverage: most
    title: Jetz Bird Range Maps
    verbatimsrs: +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs

  # Optional MoL metadata (http://www.google.com/fusiontables/DataSource?dsrcid=1348212)
  #
  Optional:
    accessright: download  view
    basemaps:
    enddateaccuracy:
    format: ESRI Shapefile
    identifier: 
    language: en
    layertype: range
    relation:
    rights:    
    startdateaccuracy:    
    surveyintervals:    
    type:

  # Mappings between collection DBF fields and MoL DBF fields: (http://www.google.com/fusiontables/DataSource?dsrcid=1348212)
  #
  DBFMapping:

    # Required MoL DBF fields 
    #
    Required:
      areaid: Latin
      bibliographiccitation: Citation
      scientificname: Latin

    # Optional MoL DBF fields
    #
    Optional:
      abundance:      
      abundancecomment:      
      abundancemakeup:      
      abundancemethod:      
      abundancesurveyarea:      
      abundanceunits:      
      areaname:      
      commonname:      
      contributor:      
      dateend:      
      datestart:      
      distributioncomment:      
      dynamicproperties:      
      establishmentmeans: OccCode
      infraspecificepithet:      
      measurementcomment:      
      measurementmethod:      
      nameaccordingto:      
      occurrencestatus:      
      polygonid:      
      polygonname:      
      population:      
      seasonality:      
      taxonid:      SpecID
      taxonremarks:

