application: mol-lab
version: axh
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /sitemap.xml
  static_files: static/config/sitemap.xml
  upload: static/config/sitemap.xml
  
- url: /robots.txt
  static_files: static/config/robots.txt
  upload: static/config/robots.txt
  
- url: /.*
  script: app.application
