application: mol-lab
version: prototype
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /hooks/.*
  script: app.py
  
- url: /admin/.*
  script: app.py
  login: admin
  
- url: /cron/.*
  script: cron.py
  login: admin

- url: /js
  static_dir: js

- url: /css
  static_dir: css
  
- url: /static
  static_dir: static

- url: /api/.*
  script: mol/api/__init__.py
 
- url: /layers/.*
  script: mol/api/__init__.py

- url: /layers
  script: mol/api/__init__.py

- url: /.*
  script: app.py
