application: map-of-life
version: canary
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

- url: /admin/.*
  script: admin_handler.application
  login: admin

- url: /tiles/.*
  script: tile_handler.application

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /cache/.*
  script: cache_handler.application

- url: /cartodb/.*
  script: cartodb_handler.application

- url: /eol/.*
  script: eol_handler.application

- url: /api/autocomplete
  script: autocomplete_handler.application

- url: /backend/.*
  script: search_cache_backend.application

- url: /.*
  script: app.application
