application: mol-apps
version: 0-1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
 
- url: /static
  static_dir: static

- url: /admin/.*
  script: AppController.py
  login: admin
  
- url: /api/.*
  script: apimethods.py
  
- url: /.*
  script: AppController.py
  
