application: map-of-life
version: canary
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /sitemap.xml
  static_files: static/config/sitemap.xml
  upload: static/config/sitemap.xml

- url: /robots.txt
  static_files: static/config/robots.txt
  upload: static/config/robots.txt

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /about.*
  script: homepage.application

- url: /
  script: app.application

- url: /.*
  script: app.application


